version: "3.8"
services:
  apache:
    container_name: local-apache
    build:
      context: ./apache
    volumes:
      - ./../:/var/www/html:cached
    restart: always
    links:
      - db
    ports:
      - 80:80

  db:
    image: mariadb:latest
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./mysql/data:/var/lib/mysql:cached
    ports:
      - '3306:3306'
      
  adminer:
    image: adminer:latest
    container_name: local-adminer
    restart: always
    ports:
      - 8080:8080